
;;; Generated by export_levels.py


.segment "DAT_BANK_00"	; Total bank size: 8176 bytes
	.export level_data_sonicwave
	level_data_sonicwave:
	; Header
		.byte song_sonic_blaster ;___ Song ID
		.byte 0 ;____________________ Starting game mode
		.byte 0 ;____________________ Starting speed
		.byte 1 ;____________________ Disable parallax
		.byte 0 ;____________________ Force platformer
		.byte _DECO1 ;_______________ Deco type
		.byte _SPIKESC ;_____________ Spike set
		.byte _BLOCKSB ;_____________ Block set
		.byte _SAWBLADESA ;__________ Sawblade set
		.byte $0F ;__________________ Starting background color
		.byte $0F ;__________________ Starting ground color
		.byte 27 ;___________________ Level height
	; Level data
		.incbin "EXPORTS/sonicwave.lz.0.bin" ; Size: 8176


.segment "DAT_BANK_01"	; Total bank size: 8176 bytes
	.export level_data_aftercatabath_3
	level_data_aftercatabath_3:
	; Level data
		.incbin "EXPORTS/aftercatabath.lz.1.bin" ; Size: 8176


.segment "DAT_BANK_02"	; Total bank size: 8171 bytes
	.export level_data_eon
	level_data_eon:
	; Header
		.byte song_eon ;_________ Song ID
		.byte 0 ;________________ Starting game mode
		.byte 1 ;________________ Starting speed
		.byte 1 ;________________ Disable parallax
		.byte 0 ;________________ Force platformer
		.byte _EXTRASPRITES1 ;___ Deco type
		.byte _SPIKESB ;_________ Spike set
		.byte _BLOCKSA ;_________ Block set
		.byte _SAWBLADESA ;______ Sawblade set
		.byte $0F ;______________ Starting background color
		.byte $0F ;______________ Starting ground color
		.byte 27 ;_______________ Level height
	; Level data
		.incbin "EXPORTS/eon.lz.0.bin" ; Size: 8171


.segment "DAT_BANK_03"	; Total bank size: 8125 bytes
	.export level_data_everyend_5
	level_data_everyend_5:
	; Level data
		.incbin "EXPORTS/everyend.lz.1.bin" ; Size: 8125


.segment "DAT_BANK_04"	; Total bank size: 8066 bytes
	.export level_data_aftercatabath
	level_data_aftercatabath:
	; Header
		.byte song_atthespeedoflightfull ;___ Song ID
		.byte 0 ;____________________________ Starting game mode
		.byte 1 ;____________________________ Starting speed
		.byte 1 ;____________________________ Disable parallax
		.byte 0 ;____________________________ Force platformer
		.byte _DECO1 ;_______________________ Deco type
		.byte _SPIKESC ;_____________________ Spike set
		.byte _BLOCKSB ;_____________________ Block set
		.byte _SAWBLADESA ;__________________ Sawblade set
		.byte $06 ;__________________________ Starting background color
		.byte $0F ;__________________________ Starting ground color
		.byte 27 ;___________________________ Level height
	; Level data
		.incbin "EXPORTS/aftercatabath.lz.0.bin" ; Size: 8066


.segment "DAT_BANK_05"	; Total bank size: 8061 bytes
	.export level_data_dearnostalgists
	level_data_dearnostalgists:
	; Header
		.byte song_crackdown ;___ Song ID
		.byte 0 ;________________ Starting game mode
		.byte 2 ;________________ Starting speed
		.byte 1 ;________________ Disable parallax
		.byte 0 ;________________ Force platformer
		.byte _EXTRASPRITES1 ;___ Deco type
		.byte _SPIKESC ;_________ Spike set
		.byte _BLOCKSA ;_________ Block set
		.byte _SAWBLADESA ;______ Sawblade set
		.byte $2C ;______________ Starting background color
		.byte $1C ;______________ Starting ground color
		.byte 57 ;_______________ Level height
	; Level data
		.incbin "EXPORTS/dearnostalgists.lz.0.bin" ; Size: 8061


.segment "DAT_BANK_06"	; Total bank size: 7997 bytes
	.export level_data_everyend
	level_data_everyend:
	; Header
		.byte song_every_end_pt1 ;___ Song ID
		.byte 0 ;____________________ Starting game mode
		.byte 0 ;____________________ Starting speed
		.byte 0 ;____________________ Disable parallax
		.byte 0 ;____________________ Force platformer
		.byte _DECO1 ;_______________ Deco type
		.byte _SPIKESA ;_____________ Spike set
		.byte _BLOCKSA ;_____________ Block set
		.byte _SAWBLADESA ;__________ Sawblade set
		.byte $11 ;__________________ Starting background color
		.byte $11 ;__________________ Starting ground color
		.byte 57 ;___________________ Level height
	; Level data
		.incbin "EXPORTS/everyend.lz.0.bin" ; Size: 7997


.segment "DAT_BANK_07"	; Total bank size: 7974 bytes
	.export level_data_windylandscape
	level_data_windylandscape:
	; Header
		.byte song_windfall ;___ Song ID
		.byte 0 ;_______________ Starting game mode
		.byte 0 ;_______________ Starting speed
		.byte 1 ;_______________ Disable parallax
		.byte 0 ;_______________ Force platformer
		.byte _DECO1 ;__________ Deco type
		.byte _SPIKESC ;________ Spike set
		.byte _BLOCKSB ;________ Block set
		.byte _SAWBLADESA ;_____ Sawblade set
		.byte $0F ;_____________ Starting background color
		.byte $0F ;_____________ Starting ground color
		.byte 27 ;______________ Level height
	; Level data
		.incbin "EXPORTS/windylandscape.lz.bin" ; Size: 7974


.segment "DAT_BANK_08"	; Total bank size: 7848 bytes
	.export level_data_ninecircles
	level_data_ninecircles:
	; Header
		.byte song_nine_circles ;___ Song ID
		.byte 0 ;___________________ Starting game mode
		.byte 0 ;___________________ Starting speed
		.byte 1 ;___________________ Disable parallax
		.byte 0 ;___________________ Force platformer
		.byte _DECO1 ;______________ Deco type
		.byte _SPIKESC ;____________ Spike set
		.byte _BLOCKSB ;____________ Block set
		.byte _SAWBLADESA ;_________ Sawblade set
		.byte $0F ;_________________ Starting background color
		.byte $0F ;_________________ Starting ground color
		.byte 27 ;__________________ Level height
	; Level data
		.incbin "EXPORTS/ninecircles.lz.bin" ; Size: 7848


.segment "DAT_BANK_09"	; Total bank size: 7802 bytes
	.export level_data_sonicblaster
	level_data_sonicblaster:
	; Header
		.byte song_sonic_blaster ;___ Song ID
		.byte 0 ;____________________ Starting game mode
		.byte 0 ;____________________ Starting speed
		.byte 1 ;____________________ Disable parallax
		.byte 0 ;____________________ Force platformer
		.byte _DECO1 ;_______________ Deco type
		.byte _SPIKESC ;_____________ Spike set
		.byte _BLOCKSB ;_____________ Block set
		.byte _SAWBLADESA ;__________ Sawblade set
		.byte $0F ;__________________ Starting background color
		.byte $0F ;__________________ Starting ground color
		.byte 25 ;___________________ Level height
	; Level data
		.incbin "EXPORTS/sonicblaster.lz.bin" ; Size: 7802


.segment "DAT_BANK_0A"	; Total bank size: 7585 bytes
	.export level_data_slaughterhouse
	level_data_slaughterhouse:
	; Header
		.byte song_lost ;_____ Song ID
		.byte 0 ;_____________ Starting game mode
		.byte 1 ;_____________ Starting speed
		.byte 1 ;_____________ Disable parallax
		.byte 0 ;_____________ Force platformer
		.byte _DECO1 ;________ Deco type
		.byte _SPIKESA ;______ Spike set
		.byte _BLOCKSB ;______ Block set
		.byte _SAWBLADESA ;___ Sawblade set
		.byte $0F ;___________ Starting background color
		.byte $0F ;___________ Starting ground color
		.byte 27 ;____________ Level height
	; Level data
		.incbin "EXPORTS/slaughterhouse.lz.bin" ; Size: 7585


.segment "DAT_BANK_0B"	; Total bank size: 7527 bytes
	.export level_data_bloodbath
	level_data_bloodbath:
	; Header
		.byte song_atthespeedoflight2 ;___ Song ID
		.byte 0 ;_________________________ Starting game mode
		.byte 0 ;_________________________ Starting speed
		.byte 1 ;_________________________ Disable parallax
		.byte 0 ;_________________________ Force platformer
		.byte _DECOCLOUD ;________________ Deco type
		.byte _SPIKESC ;__________________ Spike set
		.byte _BLOCKSB ;__________________ Block set
		.byte _SAWBLADESA ;_______________ Sawblade set
		.byte $0F ;_______________________ Starting background color
		.byte $0F ;_______________________ Starting ground color
		.byte 27 ;________________________ Level height
	; Level data
		.incbin "EXPORTS/bloodbath.lz.bin" ; Size: 7527


.segment "DAT_BANK_0C"	; Total bank size: 8177 bytes
	.export level_data_pgclubstep
	level_data_pgclubstep:
	; Header
		.byte song_clubstep ;___ Song ID
		.byte 0 ;_______________ Starting game mode
		.byte 0 ;_______________ Starting speed
		.byte 0 ;_______________ Disable parallax
		.byte 0 ;_______________ Force platformer
		.byte _DECO1 ;__________ Deco type
		.byte _SPIKESA ;________ Spike set
		.byte _BLOCKSB ;________ Block set
		.byte _SAWBLADESA ;_____ Sawblade set
		.byte $0F ;_____________ Starting background color
		.byte $0F ;_____________ Starting ground color
		.byte 50 ;______________ Level height
	; Level data
		.incbin "EXPORTS/pgclubstep.lz.bin" ; Size: 7271


.segment "DAT_BANK_0D"	; Total bank size: 7229 bytes
	.export level_data_kratos
	level_data_kratos:
	; Header
		.byte song_kratos ;___ Song ID
		.byte 0 ;_____________ Starting game mode
		.byte 0 ;_____________ Starting speed
		.byte 1 ;_____________ Disable parallax
		.byte 0 ;_____________ Force platformer
		.byte _DECO1 ;________ Deco type
		.byte _SPIKESC ;______ Spike set
		.byte _BLOCKSB ;______ Block set
		.byte _SAWBLADESA ;___ Sawblade set
		.byte $0F ;___________ Starting background color
		.byte $0F ;___________ Starting ground color
		.byte 27 ;____________ Level height
	; Level data
		.incbin "EXPORTS/kratos.lz.bin" ; Size: 7229


.segment "DAT_BANK_0E"	; Total bank size: 8190 bytes
	.export level_data_cataclysm
	level_data_cataclysm:
	; Header
		.byte song_atthespeedoflight ;___ Song ID
		.byte 0 ;________________________ Starting game mode
		.byte 1 ;________________________ Starting speed
		.byte 1 ;________________________ Disable parallax
		.byte 0 ;________________________ Force platformer
		.byte _DECO1 ;___________________ Deco type
		.byte _SPIKESC ;_________________ Spike set
		.byte _BLOCKSB ;_________________ Block set
		.byte _SAWBLADESA ;______________ Sawblade set
		.byte $06 ;______________________ Starting background color
		.byte $0F ;______________________ Starting ground color
		.byte 27 ;_______________________ Level height
	; Level data
		.incbin "EXPORTS/cataclysm.lz.bin" ; Size: 6854


.segment "DAT_BANK_0F"	; Total bank size: 8179 bytes
	.export level_data_fairydust
	level_data_fairydust:
	; Header
		.byte song_fairydust ;___ Song ID
		.byte 0 ;________________ Starting game mode
		.byte 0 ;________________ Starting speed
		.byte 1 ;________________ Disable parallax
		.byte 0 ;________________ Force platformer
		.byte _DECO1 ;___________ Deco type
		.byte _SPIKESA ;_________ Spike set
		.byte _BLOCKSB ;_________ Block set
		.byte _SAWBLADESA ;______ Sawblade set
		.byte $0F ;______________ Starting background color
		.byte $0F ;______________ Starting ground color
		.byte 27 ;_______________ Level height
	; Level data
		.incbin "EXPORTS/fairydust.lz.bin" ; Size: 6678


.segment "DAT_BANK_10"	; Total bank size: 7687 bytes
	.export level_data_invisiblelight
	level_data_invisiblelight:
	; Header
		.byte song_blacklight ;___ Song ID
		.byte 0 ;_________________ Starting game mode
		.byte 0 ;_________________ Starting speed
		.byte 1 ;_________________ Disable parallax
		.byte 0 ;_________________ Force platformer
		.byte _DECO1 ;____________ Deco type
		.byte _SPIKESA ;__________ Spike set
		.byte _BLOCKSB ;__________ Block set
		.byte _SAWBLADESA ;_______ Sawblade set
		.byte $0F ;_______________ Starting background color
		.byte $0F ;_______________ Starting ground color
		.byte 57 ;________________ Level height
	; Level data
		.incbin "EXPORTS/invisiblelight.lz.bin" ; Size: 6656


.segment "DAT_BANK_11"	; Total bank size: 6630 bytes
	.export level_data_aftermath
	level_data_aftermath:
	; Header
		.byte song_atthespeedoflight3 ;___ Song ID
		.byte 0 ;_________________________ Starting game mode
		.byte 1 ;_________________________ Starting speed
		.byte 1 ;_________________________ Disable parallax
		.byte 0 ;_________________________ Force platformer
		.byte _DECO1 ;____________________ Deco type
		.byte _SPIKESC ;__________________ Spike set
		.byte _BLOCKSB ;__________________ Block set
		.byte _SAWBLADESA ;_______________ Sawblade set
		.byte $06 ;_______________________ Starting background color
		.byte $0F ;_______________________ Starting ground color
		.byte 27 ;________________________ Level height
	; Level data
		.incbin "EXPORTS/aftermath.lz.bin" ; Size: 6630


.segment "DAT_BANK_13"	; Total bank size: 8137 bytes
	.export level_data_thermodynamix
	level_data_thermodynamix:
	; Header
		.byte song_thermodynamix ;___ Song ID
		.byte 0 ;____________________ Starting game mode
		.byte 0 ;____________________ Starting speed
		.byte 1 ;____________________ Disable parallax
		.byte 0 ;____________________ Force platformer
		.byte _DECO1 ;_______________ Deco type
		.byte _SPIKESA ;_____________ Spike set
		.byte _BLOCKSB ;_____________ Block set
		.byte _SAWBLADESA ;__________ Sawblade set
		.byte $0F ;__________________ Starting background color
		.byte $0F ;__________________ Starting ground color
		.byte 27 ;___________________ Level height
	; Level data
		.incbin "EXPORTS/thermodynamix.lz.bin" ; Size: 6356


.segment "DAT_BANK_15"	; Total bank size: 7327 bytes
	.export level_data_eighto
	level_data_eighto:
	; Header
		.byte song_eighto ;___ Song ID
		.byte 0 ;_____________ Starting game mode
		.byte 1 ;_____________ Starting speed
		.byte 1 ;_____________ Disable parallax
		.byte 0 ;_____________ Force platformer
		.byte _DECO1 ;________ Deco type
		.byte _SPIKESC ;______ Spike set
		.byte _BLOCKSC ;______ Block set
		.byte _SAWBLADESA ;___ Sawblade set
		.byte $0F ;___________ Starting background color
		.byte $0F ;___________ Starting ground color
		.byte 47 ;____________ Level height
	; Level data
		.incbin "EXPORTS/eighto.lz.bin" ; Size: 5626


.segment "DAT_BANK_16"	; Total bank size: 8181 bytes
	.export level_data_silentclubstep
	level_data_silentclubstep:
	; Header
		.byte song_clubstep ;___ Song ID
		.byte 0 ;_______________ Starting game mode
		.byte 0 ;_______________ Starting speed
		.byte 1 ;_______________ Disable parallax
		.byte 0 ;_______________ Force platformer
		.byte _DECO1 ;__________ Deco type
		.byte _SPIKESC ;________ Spike set
		.byte _BLOCKSB ;________ Block set
		.byte _SAWBLADESA ;_____ Sawblade set
		.byte $0F ;_____________ Starting background color
		.byte $0F ;_____________ Starting ground color
		.byte 57 ;______________ Level height
	; Level data
		.incbin "EXPORTS/silentclubstep.lz.bin" ; Size: 5395


.segment "DAT_BANK_17"	; Total bank size: 8136 bytes
	.export level_data_deadlyclubstep
	level_data_deadlyclubstep:
	; Header
		.byte song_clubstep ;___ Song ID
		.byte 0 ;_______________ Starting game mode
		.byte 0 ;_______________ Starting speed
		.byte 0 ;_______________ Disable parallax
		.byte 0 ;_______________ Force platformer
		.byte _DECO1 ;__________ Deco type
		.byte _SPIKESA ;________ Spike set
		.byte _BLOCKSB ;________ Block set
		.byte _SAWBLADESA ;_____ Sawblade set
		.byte $0F ;_____________ Starting background color
		.byte $0F ;_____________ Starting ground color
		.byte 40 ;______________ Level height
	; Level data
		.incbin "EXPORTS/deadlyclubstep.lz.bin" ; Size: 5140


.segment "DAT_BANK_18"	; Total bank size: 8167 bytes
	.export level_data_stalemate
	level_data_stalemate:
	; Header
		.byte song_stalemate ;___ Song ID
		.byte 0 ;________________ Starting game mode
		.byte 0 ;________________ Starting speed
		.byte 1 ;________________ Disable parallax
		.byte 0 ;________________ Force platformer
		.byte _DECO1 ;___________ Deco type
		.byte _SPIKESA ;_________ Spike set
		.byte _BLOCKSB ;_________ Block set
		.byte _SAWBLADESA ;______ Sawblade set
		.byte $0F ;______________ Starting background color
		.byte $0F ;______________ Starting ground color
		.byte 27 ;_______________ Level height
	; Level data
		.incbin "EXPORTS/stalemate.lz.bin" ; Size: 5081


.segment "DAT_BANK_19"	; Total bank size: 8000 bytes
	.export level_data_dearnostalgists_0
	level_data_dearnostalgists_0:
	; Level data
		.incbin "EXPORTS/dearnostalgists.lz.1.bin" ; Size: 4924


.segment "DAT_BANK_1B"	; Total bank size: 8164 bytes
	.export level_data_everyend_6
	level_data_everyend_6:
	; Level data
		.incbin "EXPORTS/everyend.lz.2.bin" ; Size: 4648


.segment "DAT_BANK_1C"	; Total bank size: 8192 bytes
	.export level_data_hi
	level_data_hi:
	; Header
		.byte song_miami_hotline_vol_3 ;___ Song ID
		.byte 0 ;__________________________ Starting game mode
		.byte 0 ;__________________________ Starting speed
		.byte 1 ;__________________________ Disable parallax
		.byte 0 ;__________________________ Force platformer
		.byte _DECO1 ;_____________________ Deco type
		.byte _SPIKESC ;___________________ Spike set
		.byte _BLOCKSB ;___________________ Block set
		.byte _SAWBLADESA ;________________ Sawblade set
		.byte $0F ;________________________ Starting background color
		.byte $0F ;________________________ Starting ground color
		.byte 40 ;_________________________ Level height
	; Level data
		.incbin "EXPORTS/hi.lz.bin" ; Size: 4626


.segment "DAT_BANK_1D"	; Total bank size: 8171 bytes
	.export level_data_sonicwave_2
	level_data_sonicwave_2:
	; Level data
		.incbin "EXPORTS/sonicwave.lz.1.bin" ; Size: 3319

	.export level_data_eon_1
	level_data_eon_1:
	; Level data
		.incbin "EXPORTS/eon.lz.1.bin" ; Size: 706


.segment "DAT_BANK_1E"	; Total bank size: 8188 bytes
	.export level_data_aftercatabath_4
	level_data_aftercatabath_4:
	; Level data
		.incbin "EXPORTS/aftercatabath.lz.2.bin" ; Size: 4086


.segment "DAT_BANK_20"	; Total bank size: 2571 bytes
	.export level_data_everymadness
	level_data_everymadness:
	; Header
		.byte song_every_madness ;___ Song ID
		.byte 0 ;____________________ Starting game mode
		.byte 0 ;____________________ Starting speed
		.byte 0 ;____________________ Disable parallax
		.byte 0 ;____________________ Force platformer
		.byte _DECO1 ;_______________ Deco type
		.byte _SPIKESA ;_____________ Spike set
		.byte _BLOCKSA ;_____________ Block set
		.byte _SAWBLADESA ;__________ Sawblade set
		.byte $12 ;__________________ Starting background color
		.byte $02 ;__________________ Starting ground color
		.byte 27 ;___________________ Level height
	; Level data
		.incbin "EXPORTS/everymadness.lz.bin" ; Size: 2571
